# Gradient Pillars Arena Configuration
# Не редагуйте цей файл вручну! Використовуйте команди /gp setup

arena:
  name: "Default Arena"
  world: "world"
  
  lobby:
    x: 0.0
    y: 64.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
  
  spectator:
    x: 0.0
    y: 120.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
  
  pillars:
    - x: 0.0
      y: 100.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0
    - x: 10.0
      y: 100.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0
    - x: 0.0
      y: 100.0
      z: 10.0
      yaw: 0.0
      pitch: 0.0
