name: GradientPillars
version: '${project.version}'
main: ua.xlany.gradientpillars.GradientPillars
loader: ua.xlany.gradientpillars.GradientPillarsLoader
api-version: '1.21'
author: xlanyleeet
description: Fortune Pillars minigame plugin
website: https://github.com/xlanyleeet
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false

permissions:
  gradientpillars.admin:
    description: Allows access to admin commands
    default: op
  gradientpillars.command:
    description: Allows use of the main command
    default: "true"
  gradientpillars.play:
    description: Allows joining games
    default: "true"
  gradientpillars.skipwait:
    description: Allows skipping countdown with clock item
    default: op
