name: GradientPillars
version: "${project.version}"
main: ua.xlany.gradientpillars.GradientPillars
api-version: "1.21"
description: Fortune Pillars minigame plugin
authors:
  - xlanyleeet
website: https://github.com/xlanyleeet

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false

permissions:
  gradientpillars.admin:
    description: Allows access to admin commands
    default: op
  gradientpillars.play:
    description: Allows joining games
    default: "true"
  gradientpillars.skipwait:
    description: Allows skipping countdown with clock item
    default: "false"

commands:
  gp:
    description: Main command for GradientPillars
    usage: /<command> [subcommand]
    aliases: [gradientpillars, pillars]
